FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app/server.py .

COPY app/digit_cnn.onnx .
COPY app/digit_cnn.onnx.data .
COPY app/digit_cnn_int8.onnx .

ENV MODEL_BACKEND=onnx-int8

EXPOSE 5000

CMD ["gunicorn", "--workers", "4", "--bind", "0.0.0.0:5000", "server:app"]